name: Renovate
on:
  schedule:
    # Run every Monday at 6:42 AM
    - cron: '42 6 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: 'info'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
